# This workflow will install Python dependencies and run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Maya (Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  maya2023:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Deploy Maya
      uses: docker://mottosso/maya:2023 # For all available Maya versions, see https://github.com/mottosso/docker-maya
    - name: Install dependencies
      run: |
          /usr/autodesk/maya/bin/mayapy -m pip install --upgrade pip
          pip install .
          pip install -r requirements-dev.txt
    - name: Test with pytest
      run: |
          /usr/autodesk/maya/bin/mayapy -m pytest ./tests/maya
