# This workflow will install Python dependencies and run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Maya (Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  maya2023:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    container: mottosso/maya:2023

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          wget https://bootstrap.pypa.io/pip/get-pip.py
          mayapy get-pip.py --user
          mayapy -m pip install --user \
            -r requirements-dev.txt
      - name: Environment
        run: |
          export XDG_RUNTIME_DIR=/var/tmp/runtime-root
          export MAYA_DISABLE_ADP=1
      - name: Test with pytest
        shell: bash
        run: mayapy ./tests/maya/invoke.py
